# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# github action based on Node.js CI 
# Tin 2020.0504

name: Fetch new data from covidtracking and generate new gson 


# 11:55 pm EST is 3:55 am UTC
# cron is min hour  day month  week 
on:
  schedule:
    - cron: "10 7  * *  *"
      #- cron: "15 6  4 5  1"
      #- cron: "55 3  * *  *" 
  #release:
  #  types: [created]
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        #node-version: [10.x, 12.x]
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm list
    - run: echo "running npm install next"
    - run: sudo npm install --global d3-geo-projection d3-dsv shapefile ndjson-cli json5
    - run: echo "npm list after install"
    - run: npm list
    #- run: npm ci
    #- run: npm run build --if-present
    #- run: npm test
    - run: sudo apt install dos2unix
    - run: which csv2json
    - run: pwd
    - run: ls -lah
    - run: bash -x ./fetchNewCaseDataFile.sh && bash -x ./AlgC_state+capa+case+calc.sh
    - run: git status
    - run: git diff state+capacity+cases.geojson
    - run: git config --global user.email   "sn+githubAction@grumpyxmas.com" 
    - run: git config --global user.name    "sn_github_action" 
    - run: git config --global github.user  "sn_github_action" 
    - run: export DATE=$(date) && git commit -a -m "[github action] new state+capacity+cases.geojson created on $DATE"
     
